package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"sync"
	"time"
)

// ── Material Icons codepoints proxy ────────────────────────────────────────
var (
	miMu      sync.Mutex
	miCache   map[string]string
	miCacheAt time.Time
)

const miCodepointsURL = "https://raw.githubusercontent.com/google/material-design-icons/master/font/MaterialIcons-Regular.codepoints"

func fetchMICodepoints() (map[string]string, error) {
	miMu.Lock()
	defer miMu.Unlock()
	if miCache != nil && time.Since(miCacheAt) < 24*time.Hour {
		return miCache, nil
	}
	resp, err := http.Get(miCodepointsURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("upstream %d", resp.StatusCode)
	}
	data := make(map[string]string, 2500)
	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		parts := strings.Fields(scanner.Text())
		if len(parts) == 2 {
			data[parts[0]] = parts[1]
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	miCache = data
	miCacheAt = time.Now()
	return data, nil
}

func handleMICodepoints(w http.ResponseWriter, r *http.Request) {
	enableCORS(w)
	if r.Method == "OPTIONS" {
		return
	}
	cp, err := fetchMICodepoints()
	if err != nil {
		// Serve empty map so client still works (fallback to ligature)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{})
		log.Printf("MI codepoints fetch error: %v", err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "public, max-age=86400")
	json.NewEncoder(w).Encode(cp)
}


type ExportRequest struct {
	Width    int     `json:"width"`
	Height   int     `json:"height"`
	Pixels   [][]int `json:"pixels"`
	Format   string  `json:"format"` // "micropython", "c_array", "framebuf"
	Name     string  `json:"name"`
	CropNote string  `json:"cropNote"` // optional line to inject after header
}

type ExportResponse struct {
	Code  string `json:"code,omitempty"`
	Error string `json:"error,omitempty"`
}

func enableCORS(w http.ResponseWriter) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
}

// MONO_HLSB: each row = ceil(width/8) bytes, MSB = leftmost pixel
func toMonoHLSB(pixels [][]int, width, height int) []byte {
	rowBytes := (width + 7) / 8
	buf := make([]byte, rowBytes*height)
	for y := 0; y < height && y < len(pixels); y++ {
		for x := 0; x < width; x++ {
			if x < len(pixels[y]) && pixels[y][x] == 1 {
				buf[y*rowBytes+x/8] |= 1 << (7 - x%8)
			}
		}
	}
	return buf
}

func generateMicroPython(req ExportRequest) string {
	buf      := toMonoHLSB(req.Pixels, req.Width, req.Height)
	name     := req.Name
	if name == "" { name = "image" }
	rowBytes := (req.Width + 7) / 8

	var sb strings.Builder

	// ── Section 1: Encoding reference ──────────────────────────────────────
	sb.WriteString("# ============================================================\n")
	sb.WriteString("# OLED Bitmap – Generated by OLED Pixel Designer\n")
	sb.WriteString("# MicroPython + framebuf  (MONO_HLSB format)\n")
	sb.WriteString("# ============================================================\n")
	sb.WriteString("#\n")
	sb.WriteString("# ENCODING: Horizontal / Row-Major (MONO_HLSB)\n")
	sb.WriteString("#\n")
	sb.WriteString("#   Rule 1 – Row-Major:  process pixels row by row, top → bottom.\n")
	sb.WriteString("#   Rule 2 – Left→Right: within each row, group 8 pixels per byte.\n")
	sb.WriteString("#   Rule 3 – MSB first:  bit-7 (0x80) = leftmost pixel,\n")
	sb.WriteString("#                         bit-0 (0x01) = rightmost pixel.\n")
	sb.WriteString("#   Rule 4 – Padding:    if width % 8 ≠ 0, trailing bits = 0.\n")
	sb.WriteString("#\n")
	sb.WriteString("#   Example – 8×8 \"X\" pattern:\n")
	sb.WriteString("#     Y0: #·····#  → 10000001 → 0x81\n")
	sb.WriteString("#     Y1: ·#···#·  → 01000010 → 0x42\n")
	sb.WriteString("#     Y2: ··#·#··  → 00100100 → 0x24\n")
	sb.WriteString("#     Y3: ···##··  → 00011000 → 0x18\n")
	sb.WriteString("#     ...      Result: bytearray([0x81, 0x42, 0x24, 0x18, ...])\n")
	sb.WriteString("#\n")

	// ── Section 2: Image metadata ───────────────────────────────────────────
	litCount := 0
	for _, row := range req.Pixels {
		for _, v := range row { if v == 1 { litCount++ } }
	}
	sb.WriteString(fmt.Sprintf("# Image:      %s\n", name))
	sb.WriteString(fmt.Sprintf("# Dimensions: %d × %d pixels\n", req.Width, req.Height))
	sb.WriteString(fmt.Sprintf("# Row bytes:  %d  (ceil(%d/8))\n", rowBytes, req.Width))
	sb.WriteString(fmt.Sprintf("# Array size: %d bytes  (%d rows × %d bytes/row)\n",
		len(buf), req.Height, rowBytes))
	sb.WriteString(fmt.Sprintf("# Lit pixels: %d / %d  (%.1f%%)\n",
		litCount, req.Width*req.Height, float64(litCount)/float64(req.Width*req.Height)*100))
	sb.WriteString("#\n")

	// ── Section 3: Pixel map ────────────────────────────────────────────────
	sb.WriteString("# Pixel map  (# = lit, . = off):\n#\n")
	ruler := "#     |"
	for x := 0; x < req.Width; x += 8 { ruler += fmt.Sprintf("%-8d", x) }
	sb.WriteString(ruler + "\n")
	sb.WriteString("#     +" + strings.Repeat("-", req.Width) + "\n")
	for y, row := range req.Pixels {
		if y >= req.Height { break }
		sb.WriteString(fmt.Sprintf("# %3d |%s\n", y, pixelMapLine(row)))
	}
	sb.WriteString("#\n")

	// ── Section 4: First-row byte verification ──────────────────────────────
	sb.WriteString("# Byte encoding – first 3 rows verified:\n")
	maxVerify := 3
	if req.Height < maxVerify { maxVerify = req.Height }
	for row := 0; row < maxVerify; row++ {
		start := row * rowBytes
		end   := start + rowBytes
		if end > len(buf) { end = len(buf) }
		for byteIdx := start; byteIdx < end && byteIdx-start < 2; byteIdx++ {
			col      := byteIdx - start
			pixStart := col * 8
			pixEnd   := pixStart + 8
			if pixEnd > req.Width { pixEnd = req.Width }
			var pixels []int
			if row < len(req.Pixels) { pixels = req.Pixels[row] }
			bits := ""
			for x := pixStart; x < pixStart+8; x++ {
				if x < len(pixels) && pixels[x] == 1 { bits += "1" } else { bits += "0" }
			}
			sb.WriteString(fmt.Sprintf("#   Row%2d Byte[%d] X=%2d–%2d: %s = 0x%02X\n",
				row, col, pixStart, pixEnd-1, bits, buf[byteIdx]))
		}
	}
	sb.WriteString("#\n")
	sb.WriteString("# ============================================================\n")
	if req.CropNote != "" {
		sb.WriteString(req.CropNote + "\n")
	}
	sb.WriteString("\n")

	// ── Section 5: Imports & hardware setup ────────────────────────────────
	sb.WriteString("import machine, ssd1306, framebuf\n\n")
	sb.WriteString("# I2C 設定（請依實際接線調整 Pin）\n")
	sb.WriteString("i2c = machine.I2C(0, scl=machine.Pin(22), sda=machine.Pin(21), freq=400000)\n")
	sb.WriteString(fmt.Sprintf("oled = ssd1306.SSD1306_I2C(%d, %d, i2c)\n\n", req.Width, req.Height))

	// ── Section 6: Data array – one row per line ────────────────────────────
	sb.WriteString(fmt.Sprintf("# Bitmap data – %d bytes\n", len(buf)))
	sb.WriteString(fmt.Sprintf("%s_data = bytearray([\n", name))
	for row := 0; row < req.Height; row++ {
		start := row * rowBytes
		end   := start + rowBytes
		if end > len(buf) { end = len(buf) }
		sb.WriteString(fmt.Sprintf("    # row %3d\n    ", row))
		for i := start; i < end; i++ {
			sb.WriteString(fmt.Sprintf("0x%02X", buf[i]))
			if i < len(buf)-1 { sb.WriteString(", ") }
		}
		sb.WriteString("\n")
	}
	sb.WriteString("])\n\n")

	// ── Section 7: FrameBuffer + display ───────────────────────────────────
	sb.WriteString(fmt.Sprintf("# Create FrameBuffer and blit onto OLED\n"))
	sb.WriteString(fmt.Sprintf("%s_fb = framebuf.FrameBuffer(%s_data, %d, %d, framebuf.MONO_HLSB)\n\n",
		name, name, req.Width, req.Height))
	sb.WriteString("oled.fill(0)\n")
	sb.WriteString(fmt.Sprintf("oled.blit(%s_fb, 0, 0)   # x=0, y=0; adjust as needed\n", name))
	sb.WriteString("oled.show()\n")

	return sb.String()
}

// pixelMapLine renders one pixel row as '#' (lit) / '.' (off)
func pixelMapLine(row []int) string {
	out := make([]byte, len(row))
	for i, v := range row {
		if v == 1 {
			out[i] = '#'
		} else {
			out[i] = '.'
		}
	}
	return string(out)
}

func generateCArray(req ExportRequest) string {
	buf := toMonoHLSB(req.Pixels, req.Width, req.Height)
	name := req.Name
	if name == "" {
		name = "image"
	}
	rowBytes := (req.Width + 7) / 8
	nameUP := strings.ToUpper(name)

	var sb strings.Builder

	// ── Section 1: Encoding reference ──────────────────────────────────────
	sb.WriteString("// ============================================================\n")
	sb.WriteString("// OLED Bitmap Code – Generated by OLED Pixel Designer\n")
	sb.WriteString("// ============================================================\n")
	sb.WriteString("//\n")
	sb.WriteString("// ENCODING: Horizontal / Row-Major (Adafruit_GFX standard)\n")
	sb.WriteString("//\n")
	sb.WriteString("//   Rule 1 – Row-Major:  process pixels row by row, top to bottom.\n")
	sb.WriteString("//   Rule 2 – Left→Right: within each row, group 8 pixels per byte.\n")
	sb.WriteString("//   Rule 3 – MSB first:  bit-7 (0x80) = leftmost pixel,\n")
	sb.WriteString("//                         bit-0 (0x01) = rightmost pixel.\n")
	sb.WriteString("//   Rule 4 – Padding:    if width % 8 ≠ 0, trailing bits = 0.\n")
	sb.WriteString("//\n")
	sb.WriteString("//   Example – 8×8 \"X\" pattern:\n")
	sb.WriteString("//     Y0: #·····#  → 10000001 → 0x81\n")
	sb.WriteString("//     Y1: ·#···#·  → 01000010 → 0x42\n")
	sb.WriteString("//     Y2: ··#·#··  → 00100100 → 0x24\n")
	sb.WriteString("//     Y3: ···##··  → 00011000 → 0x18\n")
	sb.WriteString("//     ...      Result: {0x81,0x42,0x24,0x18,...}\n")
	sb.WriteString("//\n")

	// ── Section 2: Image metadata ───────────────────────────────────────────
	sb.WriteString(fmt.Sprintf("// Image:      %s\n", name))
	sb.WriteString(fmt.Sprintf("// Dimensions: %d × %d pixels\n", req.Width, req.Height))
	sb.WriteString(fmt.Sprintf("// Row bytes:  %d  (ceil(%d/8))\n", rowBytes, req.Width))
	sb.WriteString(fmt.Sprintf("// Array size: %d bytes  (%d rows × %d bytes/row)\n",
		len(buf), req.Height, rowBytes))
	// Count lit pixels
	litCount := 0
	for _, row := range req.Pixels {
		for _, v := range row {
			if v == 1 {
				litCount++
			}
		}
	}
	sb.WriteString(fmt.Sprintf("// Lit pixels: %d / %d  (%.1f%%)\n",
		litCount, req.Width*req.Height, float64(litCount)/float64(req.Width*req.Height)*100))
	sb.WriteString("//\n")

	// ── Section 3: Pixel map (condensed, show '#' / '.') ───────────────────
	sb.WriteString("// Pixel map  (# = lit, . = off):\n")
	sb.WriteString("//\n")
	// Column ruler (every 8)
	ruler := "//     |"
	for x := 0; x < req.Width; x += 8 {
		ruler += fmt.Sprintf("%-8d", x)
	}
	sb.WriteString(ruler + "\n")
	sb.WriteString("//     +" + strings.Repeat("-", req.Width) + "\n")
	for y, row := range req.Pixels {
		if y >= req.Height {
			break
		}
		line := pixelMapLine(row)
		sb.WriteString(fmt.Sprintf("// %3d |%s\n", y, line))
	}
	sb.WriteString("//\n")

	// ── Section 4: First-row byte verification ─────────────────────────────
	sb.WriteString("// Byte encoding – first 3 rows verified:\n")
	maxVerify := 3
	if req.Height < maxVerify {
		maxVerify = req.Height
	}
	for row := 0; row < maxVerify; row++ {
		start := row * rowBytes
		end := start + rowBytes
		if end > len(buf) {
			end = len(buf)
		}
		for byteIdx := start; byteIdx < end && byteIdx-start < 2; byteIdx++ {
			col := byteIdx - start
			pixStart := col * 8
			pixEnd := pixStart + 8
			if pixEnd > req.Width {
				pixEnd = req.Width
			}
			var pixels []int
			if row < len(req.Pixels) {
				pixels = req.Pixels[row]
			}
			bits := ""
			for x := pixStart; x < pixStart+8; x++ {
				if x < len(pixels) && pixels[x] == 1 {
					bits += "1"
				} else {
					bits += "0"
				}
			}
			sb.WriteString(fmt.Sprintf("//   Row%2d Byte[%d] X=%2d–%2d: %s = 0x%02X\n",
				row, col, pixStart, pixEnd-1, bits, buf[byteIdx]))
		}
	}
	sb.WriteString("//\n")
	sb.WriteString("// ============================================================\n")
	if req.CropNote != "" {
		// Convert Python-style comment to C comment
		sb.WriteString(strings.ReplaceAll(req.CropNote, "#", "//") + "\n")
	}
	sb.WriteString("\n")

	// ── Section 5: Includes & defines ──────────────────────────────────────
	sb.WriteString("#include <Arduino.h>\n")
	sb.WriteString("#include <Adafruit_GFX.h>\n")
	sb.WriteString("#include <Adafruit_SSD1306.h>\n\n")
	sb.WriteString(fmt.Sprintf("#define IMG_%s_W  %d\n", nameUP, req.Width))
	sb.WriteString(fmt.Sprintf("#define IMG_%s_H  %d\n\n", nameUP, req.Height))

	// ── Section 6: Data array (one row per line) ───────────────────────────
	sb.WriteString(fmt.Sprintf("// Bitmap data – %d bytes\n", len(buf)))
	sb.WriteString(fmt.Sprintf("const uint8_t PROGMEM %s_bmp[] = {\n", name))
	for row := 0; row < req.Height; row++ {
		start := row * rowBytes
		end := start + rowBytes
		if end > len(buf) {
			end = len(buf)
		}
		sb.WriteString(fmt.Sprintf("  /* row %3d */ ", row))
		for i := start; i < end; i++ {
			sb.WriteString(fmt.Sprintf("0x%02X", buf[i]))
			if i < len(buf)-1 {
				sb.WriteString(", ")
			}
		}
		sb.WriteString("\n")
	}
	sb.WriteString("};\n\n")

	// ── Section 7: Usage ───────────────────────────────────────────────────
	sb.WriteString("// Usage:\n")
	sb.WriteString(fmt.Sprintf("// display.drawBitmap(x, y, %s_bmp, IMG_%s_W, IMG_%s_H, WHITE);\n",
		name, nameUP, nameUP))
	sb.WriteString("// display.display();\n")

	return sb.String()
}

func generateFramebuf(req ExportRequest) string {
	buf := toMonoHLSB(req.Pixels, req.Width, req.Height)
	name := req.Name
	if name == "" {
		name = "image"
	}
	rowBytes := (req.Width + 7) / 8

	var sb strings.Builder
	sb.WriteString("# Generated by OLED Pixel Designer\n")
	sb.WriteString("# MicroPython framebuf bitmap – MONO_HLSB\n")
	sb.WriteString(fmt.Sprintf("# Size: %d×%d  rowBytes: %d  total: %d bytes\n",
		req.Width, req.Height, rowBytes, len(buf)))
	if req.CropNote != "" {
		sb.WriteString(req.CropNote + "\n")
	}
	sb.WriteString("\nimport framebuf\n\n")

	// One row per line for readability
	sb.WriteString(fmt.Sprintf("%s_data = bytearray([\n", name))
	for row := 0; row < req.Height; row++ {
		start := row * rowBytes
		end := start + rowBytes
		if end > len(buf) {
			end = len(buf)
		}
		sb.WriteString(fmt.Sprintf("    # row %3d\n    ", row))
		for i := start; i < end; i++ {
			sb.WriteString(fmt.Sprintf("0x%02X", buf[i]))
			if i < len(buf)-1 {
				sb.WriteString(", ")
			}
		}
		sb.WriteString("\n")
	}
	sb.WriteString("])\n\n")

	sb.WriteString(fmt.Sprintf("%s_fb = framebuf.FrameBuffer(%s_data, %d, %d, framebuf.MONO_HLSB)\n",
		name, name, req.Width, req.Height))
	sb.WriteString(fmt.Sprintf("\n# 使用方式：\n# oled.blit(%s_fb, x, y)\n# oled.show()\n", name))
	return sb.String()
}

func handleExport(w http.ResponseWriter, r *http.Request) {
	enableCORS(w)
	if r.Method == "OPTIONS" {
		return
	}
	if r.Method != "POST" {
		http.Error(w, "method not allowed", 405)
		return
	}

	var req ExportRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(ExportResponse{Error: err.Error()})
		return
	}

	var resp ExportResponse
	switch req.Format {
	case "micropython":
		resp.Code = generateMicroPython(req)
	case "c_array":
		resp.Code = generateCArray(req)
	case "framebuf":
		resp.Code = generateFramebuf(req)
	default:
		resp.Error = "未知格式：" + req.Format
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func main() {
	http.Handle("/", http.FileServer(http.Dir("./static")))
	http.HandleFunc("/api/export", handleExport)
	http.HandleFunc("/api/material-icons", handleMICodepoints)
	port := "8090"
	log.Printf("OLED Pixel Designer 已啟動：http://localhost:%s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
