// gen_arkpixel – Pre-rasterize pixel font glyphs from BDF files
//   8px / 10px : fusion-pixel-font (zh_hant, full CJK coverage)
//   12px / 16px: ark-pixel-font   (zh_tw,   full CJK coverage)
// Downloads BDF zips from GitHub releases, parses ALL glyphs, outputs arkpixel.js
// Usage: go run main.go > ../../static/js/arkpixel.js

package main

import (
	"archive/zip"
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const arkVersion    = "2026.05.07"
const fusionVersion = "2026.05.07"

const arkBaseURL    = "https://github.com/TakWolf/ark-pixel-font/releases/download/" + arkVersion
const fusionBaseURL = "https://github.com/TakWolf/fusion-pixel-font/releases/download/" + fusionVersion

type Glyph struct{ W, H int; Rows []uint32 }

// sizeSpec describes where to download a specific pixel size.
type sizeSpec struct {
	sz        int
	baseURL   string
	prefix    string // e.g. "ark-pixel" or "fusion-pixel"
	zhVariant string // e.g. "zh_tw" or "zh_hant"
}

var sizes = []sizeSpec{
	{8,  fusionBaseURL, "fusion-pixel", "zh_hant"},
	{10, fusionBaseURL, "fusion-pixel", "zh_hant"},
	{12, arkBaseURL,    "ark-pixel",    "zh_tw"},
	{16, arkBaseURL,    "ark-pixel",    "zh_tw"},
}

// parseBDF reads a BDF file and returns all glyphs with ENCODING >= 32.
func parseBDF(data []byte) map[rune]*Glyph {
	glyphs := map[rune]*Glyph{}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 1<<20), 1<<20)

	var encoding rune = -1
	var bbxW int
	var inBitmap bool
	var rowIdx int
	var curRows []uint32
	var bytesPerRow int

	for scanner.Scan() {
		line := scanner.Text()
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "ENCODING":
			n, _ := strconv.Atoi(fields[1])
			encoding = rune(n)
		case "BBX":
			w, _ := strconv.Atoi(fields[1])
			h, _ := strconv.Atoi(fields[2])
			bbxW = w
			bytesPerRow = (w + 7) / 8
			curRows = make([]uint32, h)
			rowIdx = 0
		case "BITMAP":
			inBitmap = encoding >= 32
			rowIdx = 0
		case "ENDCHAR":
			if inBitmap && encoding >= 32 {
				top, bot := len(curRows), -1
				for y, r := range curRows {
					if r != 0 {
						if y < top { top = y }
						if y > bot { bot = y }
					}
				}
				var g *Glyph
				if bot < top {
					g = &Glyph{W: bbxW, H: 1, Rows: []uint32{0}}
				} else {
					trimmed := make([]uint32, bot-top+1)
					copy(trimmed, curRows[top:bot+1])
					g = &Glyph{W: bbxW, H: bot - top + 1, Rows: trimmed}
				}
				glyphs[encoding] = g
			}
			inBitmap = false
			encoding = -1
		default:
			if inBitmap && rowIdx < len(curRows) {
				// BDF rows are MSB-first, padded to byte boundary.
				// Shift right by padding bits so leftmost pixel is in MSB position.
				n, _ := strconv.ParseUint(fields[0], 16, 64)
				padBits := uint(bytesPerRow*8 - bbxW)
				curRows[rowIdx] = uint32(n >> padBits)
				rowIdx++
			}
		}
	}
	return glyphs
}

func fetchZip(url string) (*zip.Reader, error) {
	fmt.Fprintf(os.Stderr, "Downloading %s ...\n", url)
	resp, err := http.Get(url) //nolint:noctx
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return zip.NewReader(bytes.NewReader(data), int64(len(data)))
}

func readFromZip(zr *zip.Reader, name string) ([]byte, error) {
	for _, f := range zr.File {
		if f.Name == name {
			rc, err := f.Open()
			if err != nil {
				return nil, err
			}
			defer rc.Close()
			return io.ReadAll(rc)
		}
	}
	return nil, fmt.Errorf("file %q not found in zip", name)
}

func jsKey(ch rune) string {
	switch ch {
	case '\'':
		return `"'"`
	case '"':
		return `'"'`
	case '\\':
		return `'\\'`
	}
	if ch <= 126 {
		return fmt.Sprintf("'%c'", ch)
	}
	return fmt.Sprintf("'\\u%04X'", ch)
}

func main() {
	fmt.Println("// Generated by tools/gen_arkpixel/main.go – DO NOT EDIT")
	fmt.Println("//   8px / 10px : fusion-pixel-font (zh_hant)")
	fmt.Println("//   12px / 16px: ark-pixel-font   (zh_tw)")
	fmt.Println("// Regenerate: cd tools/gen_arkpixel && go run main.go > ../../static/js/arkpixel.js")
	fmt.Println("/* global ARKPIXEL */")
	fmt.Println("const ARKPIXEL = {};")

	for _, spec := range sizes {
		zipURL := fmt.Sprintf("%s/%s-font-%dpx-monospaced-bdf-v%s.zip",
			spec.baseURL, spec.prefix, spec.sz,
			func() string {
				if spec.baseURL == arkBaseURL { return arkVersion }
				return fusionVersion
			}())
		zr, err := fetchZip(zipURL)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}

		latinName := fmt.Sprintf("%s-%dpx-monospaced-latin.bdf", spec.prefix, spec.sz)
		zhName    := fmt.Sprintf("%s-%dpx-monospaced-%s.bdf",   spec.prefix, spec.sz, spec.zhVariant)

		latinData, err := readFromZip(zr, latinName)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		zhData, err := readFromZip(zr, zhName)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}

		// Merge: zh variant first, then latin overrides (latin authoritative for ASCII/Latin)
		glyphs := parseBDF(zhData)
		for r, g := range parseBDF(latinData) {
			glyphs[r] = g
		}

		// Sort by codepoint
		chars := make([]rune, 0, len(glyphs))
		for r := range glyphs {
			chars = append(chars, r)
		}
		sort.Slice(chars, func(i, j int) bool { return chars[i] < chars[j] })

		fmt.Printf("\nARKPIXEL[%d] = {\n", spec.sz)
		for i, ch := range chars {
			g := glyphs[ch]
			rowStrs := make([]string, len(g.Rows))
			for j, row := range g.Rows {
				rowStrs[j] = fmt.Sprintf("0x%X", row)
			}
			comma := ","
			if i == len(chars)-1 {
				comma = ""
			}
			fmt.Printf("  %s:{w:%d,h:%d,rows:[%s]}%s\n",
				jsKey(ch), g.W, g.H, strings.Join(rowStrs, ","), comma)
		}
		fmt.Println("};")
		fmt.Fprintf(os.Stderr, "size=%dpx (%s): %d glyphs\n", spec.sz, spec.prefix, len(chars))
	}

	fmt.Print(`
function arkpixelGrid(ch, size) {
  const t = ARKPIXEL[size]; if (!t) return null;
  const g = t[ch]; if (!g) return null;
  const {w, h, rows} = g;
  return rows.map(row => Array.from({length:w}, (_,x) => (row >>> (w-1-x)) & 1));
}

function arkpixelText(text, size, spacing) {
  const sp = (spacing !== undefined ? spacing : 1);
  const grids = [];
  for (const ch of text) {
    grids.push(arkpixelGrid(ch, size) || arkpixelGrid(' ', size) || [[0]]);
  }
  if (!grids.length) return null;
  const h = Math.max(...grids.map(g => g.length));
  const totalW = grids.reduce((s,g) => s+(g[0]?.length||0), 0) + (grids.length-1)*sp;
  const out = Array.from({length:h}, () => new Array(totalW).fill(0));
  let x = 0;
  for (const g of grids) {
    const cw = g[0]?.length||0, ch2 = g.length, yOff = h - ch2;
    for (let y=0; y<ch2; y++) for (let cx=0; cx<cw; cx++) out[yOff+y][x+cx] = g[y][cx];
    x += cw + sp;
  }
  let top=h, bot=-1;
  for (let y=0;y<h;y++) for (let cx=0;cx<totalW;cx++) if(out[y][cx]){if(y<top)top=y;if(y>bot)bot=y;}
  if(bot<0) return {grid:[[0]],width:1,height:1};
  return {grid:out.slice(top,bot+1), width:totalW, height:bot-top+1};
}
`)
}
